baseURL = 'https://ivyfri.github.io/portfolio/'
languageCode = 'en-us'
title = 'Ivyfri portfolio'
theme = 'hello-friend-ng'

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 2

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 3
